-- VERY IMPORTANT so that the stream is from beginning of Kafka topic
SET 'auto.offset.reset' = 'earliest';

CREATE OR REPLACE STREAM lndcdcadsprpsl_prpslotlt_stream (_ID STRING KEY) 
with (KAFKA_TOPIC='lndcdcadsprpsl_prpslotlt', VALUE_FORMAT='AVRO');

SHOW STREAMS;

DESCIBE EXTENDED LNDCDCADSPRPSL_PRPSLOTLT_STREAM;

```
Name                 : LNDCDCADSPRPSL_PRPSLOTLT_STREAM
Type                 : STREAM
Timestamp field      : Not set - using <ROWTIME>
Key format           : KAFKA
Value format         : AVRO
Kafka topic          : lndcdcadsprpsl_prpslotlt (partitions: 8, replication: 3)
Statement            : CREATE OR REPLACE STREAM LNDCDCADSPRPSL_PRPSLOTLT_STREAM (_ID STRING KEY, PRPSL_OTLT_ID BIGINT, LAST_MODIFIED_BY STRING, LAST_MODIFIED_DT STRING, PROPOSAL_ID BIGINT, OUTLET_EXTENSION_ID BIGINT, PRIM_INVNTRY_TYP_ID BIGINT, PRIM_UNIT_LGTH_ID BIGINT, PRIM_UNIT_QTY BIGINT, SEC_INVNTRY_TYP_ID BIGINT, SEC_UNIT_LGTH_ID BIGINT, SEC_UNIT_QTY BIGINT, SRC_SYS_APP_RGSTRY_ID BIGINT, CNCRNCY_VRSN BIGINT, SRC_KEY_VAL STRING, SRC_CDC_OPER_NM STRING, SRC_COMMIT_DT_UTC STRING, TRG_CRT_DT_PART_UTC STRING, SRC_SCHEMA_NM STRING) WITH (KAFKA_TOPIC='lndcdcadsprpsl_prpslotlt', KEY_FORMAT='KAFKA', VALUE_FORMAT='AVRO', VALUE_SCHEMA_ID=355);

 Field                 | Type                   
------------------------------------------------
 _ID                   | VARCHAR(STRING)  (key) 
 PRPSL_OTLT_ID         | BIGINT                 
 LAST_MODIFIED_BY      | VARCHAR(STRING)        
 LAST_MODIFIED_DT      | VARCHAR(STRING)        
 PROPOSAL_ID           | BIGINT                 
 OUTLET_EXTENSION_ID   | BIGINT                 
 PRIM_INVNTRY_TYP_ID   | BIGINT                 
 PRIM_UNIT_LGTH_ID     | BIGINT                 
 PRIM_UNIT_QTY         | BIGINT                 
 SEC_INVNTRY_TYP_ID    | BIGINT                 
 SEC_UNIT_LGTH_ID      | BIGINT                 
 SEC_UNIT_QTY          | BIGINT                 
 SRC_SYS_APP_RGSTRY_ID | BIGINT                 
 CNCRNCY_VRSN          | BIGINT                 
 SRC_KEY_VAL           | VARCHAR(STRING)        
 SRC_CDC_OPER_NM       | VARCHAR(STRING)        
 SRC_COMMIT_DT_UTC     | VARCHAR(STRING)        
 TRG_CRT_DT_PART_UTC   | VARCHAR(STRING)        
 SRC_SCHEMA_NM         | VARCHAR(STRING)        
------------------------------------------------

Queries that read from this STREAM
-----------------------------------
CTAS_LNDCDCADSPRPSL_PRPSLOTLT_RECORD_COUNTER_TBL_263 (RUNNING) : CREATE OR REPLACE TABLE LNDCDCADSPRPSL_PRPSLOTLT_RECORD_COUNTER_TBL WITH (KAFKA_TOPIC='LNDCDCADSPRPSL_PRPSLOTLT_RECORD_COUNTER_TBL', PARTITIONS=8, REPLICAS=3) AS SELECT   LNDCDCADSPRPSL_PRPSLOTLT_STREAM._ID KAFKA_KEY_AS_TBL_PK,   LATEST_BY_OFFSET(LNDCDCADSPRPSL_PRPSLOTLT_STREAM.PRPSL_OTLT_ID) PRPSL_OTLT_ID,   EARLIEST_BY_OFFSET(LNDCDCADSPRPSL_PRPSLOTLT_STREAM.CNCRNCY_VRSN, false) MIN_CNCRNCY_VRSN,   LATEST_BY_OFFSET(LNDCDCADSPRPSL_PRPSLOTLT_STREAM.CNCRNCY_VRSN, false) MAX_CNCRNCY_VRSN,   EARLIEST_BY_OFFSET(LNDCDCADSPRPSL_PRPSLOTLT_STREAM.SRC_CDC_OPER_NM) MIN_OPER,   LATEST_BY_OFFSET(LNDCDCADSPRPSL_PRPSLOTLT_STREAM.SRC_CDC_OPER_NM) MAX_OPER,   COUNT(LNDCDCADSPRPSL_PRPSLOTLT_STREAM.SRC_CDC_OPER_NM) TOTAL_RECORDS FROM LNDCDCADSPRPSL_PRPSLOTLT_STREAM LNDCDCADSPRPSL_PRPSLOTLT_STREAM GROUP BY LNDCDCADSPRPSL_PRPSLOTLT_STREAM._ID EMIT CHANGES;
CTAS_LNDCDCADSPRPSL_PRPSLOTLT_MAT_TBL_237 (RUNNING) : CREATE OR REPLACE TABLE LNDCDCADSPRPSL_PRPSLOTLT_MAT_TBL WITH (KAFKA_TOPIC='LNDCDCADSPRPSL_PRPSLOTLT_MAT_TBL', PARTITIONS=8, REPLICAS=3) AS SELECT   LNDCDCADSPRPSL_PRPSLOTLT_STREAM._ID KAFKA_KEY_AS_TBL_PK,   LATEST_BY_OFFSET(LNDCDCADSPRPSL_PRPSLOTLT_STREAM.PRPSL_OTLT_ID) PRPSL_OTLT_ID,   LATEST_BY_OFFSET(LNDCDCADSPRPSL_PRPSLOTLT_STREAM.LAST_MODIFIED_BY) LAST_MODIFIED_BY,   LATEST_BY_OFFSET(LNDCDCADSPRPSL_PRPSLOTLT_STREAM.LAST_MODIFIED_DT) LAST_MODIFIED_DT,   LATEST_BY_OFFSET(LNDCDCADSPRPSL_PRPSLOTLT_STREAM.PROPOSAL_ID) PROPOSAL_ID,   LATEST_BY_OFFSET(LNDCDCADSPRPSL_PRPSLOTLT_STREAM.OUTLET_EXTENSION_ID) OUTLET_EXTENSION_ID,   LATEST_BY_OFFSET(LNDCDCADSPRPSL_PRPSLOTLT_STREAM.PRIM_INVNTRY_TYP_ID) PRIM_INVNTRY_TYP_ID,   LATEST_BY_OFFSET(LNDCDCADSPRPSL_PRPSLOTLT_STREAM.PRIM_UNIT_LGTH_ID) PRIM_UNIT_LGTH_ID,   LATEST_BY_OFFSET(LNDCDCADSPRPSL_PRPSLOTLT_STREAM.PRIM_UNIT_QTY) PRIM_UNIT_QTY,   LATEST_BY_OFFSET(LNDCDCADSPRPSL_PRPSLOTLT_STREAM.SEC_INVNTRY_TYP_ID) SEC_INVNTRY_TYP_ID,   LATEST_BY_OFFSET(LNDCDCADSPRPSL_PRPSLOTLT_STREAM.SEC_UNIT_LGTH_ID) SEC_UNIT_LGTH_ID,   LATEST_BY_OFFSET(LNDCDCADSPRPSL_PRPSLOTLT_STREAM.SEC_UNIT_QTY) SEC_UNIT_QTY,   LATEST_BY_OFFSET(LNDCDCADSPRPSL_PRPSLOTLT_STREAM.SRC_SYS_APP_RGSTRY_ID) SRC_SYS_APP_RGSTRY_ID,   LATEST_BY_OFFSET(LNDCDCADSPRPSL_PRPSLOTLT_STREAM.CNCRNCY_VRSN) CNCRNCY_VRSN,   LATEST_BY_OFFSET(LNDCDCADSPRPSL_PRPSLOTLT_STREAM.SRC_CDC_OPER_NM) SRC_CDC_OPER_NM,   LATEST_BY_OFFSET(LNDCDCADSPRPSL_PRPSLOTLT_STREAM.SRC_COMMIT_DT_UTC) SRC_COMMIT_DT_UTC,   LATEST_BY_OFFSET(LNDCDCADSPRPSL_PRPSLOTLT_STREAM.TRG_CRT_DT_PART_UTC) TRG_CRT_DT_PART_UTC FROM LNDCDCADSPRPSL_PRPSLOTLT_STREAM LNDCDCADSPRPSL_PRPSLOTLT_STREAM GROUP BY LNDCDCADSPRPSL_PRPSLOTLT_STREAM._ID EMIT CHANGES;
```